travis:
  secure:
    BINSTAR_TOKEN: Cr4NOBZrHX84lQs+cSbiylyTjz5o2vT2FPv9QNpj8Pa9fO60qaCXRnfZLqQoMvi85bUczEsfG4Fpu6jR7zyFnM2+3QbHjJudDNvMrOh0RvgJDnTYSeHL/3l5W0WRjYOmQ5cCRtXgLgGshsCGSmqkAnEMjTwo7Jh5wAVBi37nktIY8KWlxeTYSI+/zt1sqWXhxbvPim2PYftv9V2+VrN4AxqdPPU0Jecw5Q8ziH99OLN9sX1ZeNuJ24Skw6c7X1x0RYdieF1UFORAxVmpgpRUdsV7PyjaeZRxGnAaWnmXiGaoc1x7w6HzR0AUTFyJaGfuQOnC/IXiyZ/yKu98/Z4Ki1vHYdmj9q/CJ9frm8DUF0xq1omfB5uiEOn6RqZxe0XghKUcJRi1S4X45a1pYzZIqlhFGCKTRm7wdj5U51UH73PoNkpAYp2r9Mj/P6IceqDTrX6v9lU434psgaPTV/J1rILa4ySNRhuy8m1KDioCGrsp/vcZIXfs2X/bxSk8b7KHX5140ewNO/qoJ+ivk5Cjxw3KGn9vQOulE8dIafRj3BJgW2i64x6GFmKaypBJltj21nFH4Wlf87bXPPylscqDK+ZkTM6nLA8HBf+O+6wxYm3GX3xcGQqFi+CoTwPdcIixLGDXODUWOm9q2SoS1JKmM5+171UVX69lTS1+DEHMEH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
